#
#
version: '3'

networks:
  hyperledger-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  aries-javascript:
    env_file:
      - ./.env
    build: ./
    image: aries-javascript
    container_name: aries-javascript
    working_dir: /www
    volumes:
     - ./:/www
     - node_modules:/www/node_modules
    networks:
      - hyperledger-network
    tty: true
volumes:
  node_modules:
  db_data: {}
