version: '3'

services:
  http-mediator:
    build: ..
    image: aries-framework-javascript
    container_name: afj-http-mediator
    command: yarn mediator:start
    platform: linux/amd64
    networks:
      - hyperledger
    ports:
      - 3001:3001

  ws-mediator:
    build: ..
    image: aries-framework-javascript
    container_name: afj-ws-mediator
    command: yarn mediator:start-ws
    platform: linux/amd64
    networks:
      - hyperledger
    ports:
      - 3002:3002

networks:
  hyperledger:
