name: Run mediator agents
description: Start multiple mediator agents
author: 'timo@animo.id'

runs:
  using: composite
  steps:
    - name: Start mediator agents
      run: docker-compose -f docker/docker-compose-mediators.yml up -d
      shell: bash

branding:
  icon: scissors
  color: purple
