name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  TEST_AGENT_PUBLIC_DID_SEED: 000000000000000000000000Trustee9
  GENESIS_TXN_PATH: network/genesis/local-genesis.txn

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/todogroup/repolinter:v0.10.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Repo
        run: bundle exec /app/bin/repolinter.js --rulesetFile repolint.json
  integration-test:
    runs-on: ubuntu-18.04
    name: Integration Tests
    steps:
      - name: Checkout aries-framework-javascript
        uses: actions/checkout@v2

      - name: Get docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Start indy pool
        run: |
          docker build -f network/indy-pool.dockerfile -t indy-pool .
          docker run -d --name indy-pool -p 9701-9708:9701-9708 indy-pool
          docker exec indy-pool indy-cli-setup

      - name: Register DID on ledger
        run: docker exec indy-pool add-did-from-seed "${TEST_AGENT_PUBLIC_DID_SEED}"

      - name: Build framework docker image
        run: docker build -t aries-framework-javascript .

      - name: Run lint and format validation
        run: docker run aries-framework-javascript yarn validate

      - name: Start mediator agents
        run: docker-compose -f docker/docker-compose-mediators.yml up -d

      - name: Run tests
        run: >-
          docker run 
          --network host
          --name framework-jest-tests 
          --env TEST_AGENT_PUBLIC_DID_SEED=${TEST_AGENT_PUBLIC_DID_SEED}
          --env GENESIS_TXN_PATH=${GENESIS_TXN_PATH}
          aries-framework-javascript 
          yarn test --coverage

      - name: Export logs
        if: always()
        run: |
          mkdir logs
          docker cp alice-mediator:/www/logs.txt ./logs/alice-mediator.txt
          docker cp bob-mediator:/www/logs.txt ./logs/bob-mediator.txt
          docker cp framework-jest-tests:/www/logs.txt ./logs/jest.txt

      - name: Upload docker logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: docker-logs
          path: logs

      - name: Export test coverage
        if: always()
        run: docker cp framework-jest-tests:/www/coverage ./
      - uses: codecov/codecov-action@v1
        if: always()
